# Generated by Django 4.2.30 on 2026-07-13 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_issuetemplate_recurringissue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description_html', models.TextField(blank=True, default='<p></p>')),
                ('status', models.CharField(choices=[('PLANNED', 'Direncanakan'), ('ACTIVE', 'Berjalan'), ('ON_HOLD', 'Ditunda'), ('COMPLETED', 'Selesai')], default='PLANNED', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives_lead', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
                'db_table': 'initiatives',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InitiativeProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_projects', to='db.initiative')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_initiatives', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_projects', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Initiative Project',
                'verbose_name_plural': 'Initiative Projects',
                'db_table': 'initiative_projects',
                'ordering': ('-created_at',),
                'unique_together': {('initiative', 'project', 'deleted_at')},
            },
        ),
        migrations.AddField(
            model_name='initiative',
            name='projects',
            field=models.ManyToManyField(related_name='initiatives', through='db.InitiativeProject', to='db.project'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='db.workspace'),
        ),
    ]
