# Generated by Django 4.2.30 on 2026-07-24 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0125_initiative_initiativeproject_initiative_projects_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiGovernedProject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_governance', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_governed_projects', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Wiki Governed Project',
                'verbose_name_plural': 'Wiki Governed Projects',
                'db_table': 'wiki_governed_projects',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='WikiFolderAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_division_access', to='db.project')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_folder_access', to='db.page')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_folder_access', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_folder_access', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Wiki Folder Access',
                'verbose_name_plural': 'Wiki Folder Access',
                'db_table': 'wiki_folder_access',
                'ordering': ('-created_at',),
                'unique_together': {('folder', 'division', 'deleted_at')},
            },
        ),
    ]
