# Generated by Django 4.2.30 on 2026-07-28 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_wikigovernedproject_wikifolderaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikigovernedproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wiki_governance', to='db.project'),
        ),
        migrations.AlterUniqueTogether(
            name='wikigovernedproject',
            unique_together={('project', 'deleted_at')},
        ),
    ]
