# Generated by Django 4.2.30 on 2026-08-07 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0127_alter_wikigovernedproject_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginActivity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('jenis', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=10)),
                ('terjadi_pada', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ip', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.TextField(blank=True)),
                ('medium', models.CharField(blank=True, max_length=20)),
                ('permukaan', models.CharField(blank=True, max_length=10)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Login Activity',
                'verbose_name_plural': 'Login Activities',
                'db_table': 'login_activities',
                'ordering': ('-terjadi_pada',),
                'indexes': [models.Index(fields=['user', '-terjadi_pada'], name='loginact_user_waktu_idx'), models.Index(fields=['jenis', '-terjadi_pada'], name='loginact_jenis_waktu_idx')],
            },
        ),
    ]
