# Generated by Django 4.2.30 on 2026-08-12 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_pengingattenggat'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcaraKalender',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('google_event_id', models.CharField(max_length=1024)),
                ('tenggat', models.DateField()),
                ('judul', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Acara Kalender',
                'verbose_name_plural': 'Acara Kalender',
                'db_table': 'calendar_events',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='KalenderGoogle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('refresh_token', models.TextField()),
                ('akun_email', models.EmailField(blank=True, max_length=254)),
                ('calendar_id', models.CharField(default='primary', max_length=255)),
                ('terakhir_sinkron', models.DateTimeField(blank=True, null=True)),
                ('galat_terakhir', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Kalender Google',
                'verbose_name_plural': 'Kalender Google',
                'db_table': 'google_calendars',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RenameIndex(
            model_name='pengingattenggat',
            new_name='deadline_re_issue_i_e8b507_idx',
            old_name='deadline_re_issue_i_8f3a21_idx',
        ),
        migrations.AddField(
            model_name='kalendergoogle',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='kalendergoogle',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='kalendergoogle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='google_calendars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='acarakalender',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='acarakalender',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='db.issue'),
        ),
        migrations.AddField(
            model_name='acarakalender',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='acarakalender',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='kalendergoogle',
            unique_together={('user', 'deleted_at')},
        ),
        migrations.AddIndex(
            model_name='acarakalender',
            index=models.Index(fields=['user', 'issue'], name='calendar_ev_user_id_2d210c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acarakalender',
            unique_together={('user', 'issue', 'deleted_at')},
        ),
    ]
