# Generated by Django 4.2.30 on 2026-08-12 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0131_kalendergoogle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kalendergoogle',
            name='akun_email',
        ),
    ]
