# Generated by Django 4.2.30 on 2026-08-18 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid



def bangun_ruang_dari_dm_lama(apps, schema_editor):
    """Beri ruang kepada setiap pesan yang sudah ada.

    Sesudah migrasi ini, TIDAK BOLEH ada satu pun pesan tanpa ruang. Chat ini
    sudah dipakai orang sungguhan, jadi pesan yatim berarti percakapan yang
    hilang dari layar pemiliknya tanpa jejak error di mana pun.

    Baris yang sudah dihapus lunak ikut diproses. Mereka tetap baris di tabel,
    dan menyisakannya tanpa ruang berarti menaruh ranjau untuk kueri mana pun
    yang nanti memakai `ruang` tanpa memikirkan `deleted_at`.
    """
    PesanLangsung = apps.get_model("db", "PesanLangsung")
    Ruang = apps.get_model("db", "Ruang")
    Langganan = apps.get_model("db", "Langganan")

    pesan_lama = PesanLangsung.objects.all().order_by("created_at")
    if not pesan_lama.exists():
        return

    # Kelompokkan per pasangan. Kuncinya diurutkan supaya A-ke-B dan B-ke-A
    # jatuh ke ruang yang SAMA. Kalau tidak, dua orang yang saling membalas
    # akan berakhir di dua ruang terpisah dan separuh riwayatnya lenyap.
    per_pasangan = {}
    for pesan in pesan_lama.iterator():
        kunci = ":".join(sorted([str(pesan.pengirim_id), str(pesan.penerima_id)]))
        per_pasangan.setdefault((pesan.workspace_id, kunci), []).append(pesan)

    for (workspace_id, kunci), daftar in per_pasangan.items():
        ruang = Ruang.objects.create(
            workspace_id=workspace_id,
            tipe="dm",
            kunci_dm=kunci,
            pesan_terakhir_pada=max(p.created_at for p in daftar),
        )
        PesanLangsung.objects.filter(id__in=[p.id for p in daftar]).update(ruang=ruang)

        for user_id in kunci.split(":"):
            # Pindahkan status baca dari penanda per-pesan ke satu cap waktu.
            # Yang dicari: pesan MASUK terbaru yang sudah ditandai terbaca.
            # Tanpa langkah ini semua percakapan lama mendadak muncul sebagai
            # belum dibaca, dan 90 orang membuka aplikasi dengan lencana merah
            # untuk pesan yang sudah lama mereka baca.
            terbaca = [
                p.created_at
                for p in daftar
                if str(p.penerima_id) == user_id and p.dibaca_pada is not None
            ]
            Langganan.objects.create(
                ruang=ruang,
                user_id=user_id,
                dibaca_sampai=max(terbaca) if terbaca else None,
            )


def lepas_ruang(apps, schema_editor):
    """Balikan: lepaskan pesan dari ruang lalu buang ruangnya.

    Pesannya sendiri tidak disentuh, karena `penerima` dan `dibaca_pada` masih
    utuh di setiap baris. Jadi mundur dari migrasi ini tidak kehilangan apa pun.
    """
    apps.get_model("db", "PesanLangsung").objects.update(ruang=None)
    apps.get_model("db", "Langganan").objects.all().delete()
    apps.get_model("db", "Ruang").objects.all().delete()
    # Postgres menunda pemeriksaan kunci asing sampai transaksi ditutup, lalu
    # menolak ALTER TABLE berikutnya dengan "pending trigger events". Operasi
    # skema yang menyusul di migrasi ini kena persis itu. Memaksa pemeriksaan
    # sekarang menyelesaikan trigger yang tertunda selagi transaksi masih hidup.
    schema_editor.execute("SET CONSTRAINTS ALL IMMEDIATE")


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0135_chat_sunting_balasan_reaksi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Langganan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('dibaca_sampai', models.DateTimeField(blank=True, null=True)),
                ('notifikasi', models.CharField(choices=[('semua', 'Semua pesan'), ('mention', 'Hanya kalau disebut'), ('mati', 'Bisukan')], default='semua', max_length=10)),
                ('disematkan', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Langganan Ruang',
                'verbose_name_plural': 'Langganan Ruang',
                'db_table': 'chat_subscriptions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Ruang',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tipe', models.CharField(choices=[('dm', 'Pesan Langsung'), ('kanal', 'Kanal Publik'), ('privat', 'Kanal Privat')], default='dm', max_length=10)),
                ('nama', models.CharField(blank=True, max_length=80, null=True)),
                ('topik', models.CharField(blank=True, default='', max_length=255)),
                ('kunci_dm', models.CharField(blank=True, max_length=73, null=True, unique=True)),
                ('pesan_terakhir_pada', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ruang Obrolan',
                'verbose_name_plural': 'Ruang Obrolan',
                'db_table': 'chat_rooms',
                'ordering': ('-pesan_terakhir_pada',),
            },
        ),
        migrations.AlterField(
            model_name='pesanlangsung',
            name='penerima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesan_diterima', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ruang',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ruang',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='ruang',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruang_obrolan', to='db.workspace'),
        ),
        migrations.AddField(
            model_name='langganan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='langganan',
            name='ruang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langganan', to='db.ruang'),
        ),
        migrations.AddField(
            model_name='langganan',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By'),
        ),
        migrations.AddField(
            model_name='langganan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='langganan_ruang', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pesanlangsung',
            name='ruang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pesan', to='db.ruang'),
        ),
        # Indeks WAJIB sesudah kolomnya ada. makemigrations menaruhnya
        # lebih dulu dan migrasi meledak dengan FieldDoesNotExist.
        migrations.AddIndex(
            model_name='pesanlangsung',
            index=models.Index(fields=['ruang', 'created_at'], name='dm_ruang_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ruang',
            index=models.Index(fields=['workspace', 'tipe'], name='ruang_ws_tipe_idx'),
        ),
        migrations.AddIndex(
            model_name='ruang',
            index=models.Index(fields=['workspace', 'pesan_terakhir_pada'], name='ruang_ws_terakhir_idx'),
        ),
        migrations.AddIndex(
            model_name='langganan',
            index=models.Index(fields=['user', 'ruang'], name='langganan_user_ruang_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='langganan',
            unique_together={('ruang', 'user', 'deleted_at')},
        ),
        # Terakhir, sesudah semua kolom dan indeks ada.
        migrations.RunPython(bangun_ruang_dari_dm_lama, lepas_ruang),
    ]
